# Generated by Django 4.1.3 on 2022-12-26 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_postcategory_subscribers_alter_post_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
