# Generated by Django 4.1.3 on 2023-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_comment_dislikes_comment_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'статья'), ('NW', 'Новость')], default='NW', max_length=2),
        ),
    ]
