# Generated by Django 4.1.3 on 2023-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'article'), ('NW', 'news')], default='NW', max_length=2),
        ),
    ]
