# Generated by Django 4.1.3 on 2024-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_postcategory_options_alter_author_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0, verbose_name='Автор публикации'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Name of category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
