# Generated by Django 4.1.3 on 2024-05-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_author_author_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
